CHANGELOG.md, github/ISSUE_TEMPLATE/bug_report.md, github/ISSUE_TEMPLATE/feature_request.md, github/PULL_REQUEST_TEMPLATE.md, manifest.json, react/queries/searchQuery.gql
This impacts the SEO analysis. 
https://searchquery--storecomponents.myvtexdev.com/shoes/d
=> Remove description of the product to search query

CHANGELOG.md, manifest.json, react/queries/orderForm.gql
as title says:
you can test at 
https://fidbeta2--delivery.myvtex.com/
or
https://fidelis--storecomponents.myvtex.com/
Related to: https://github.com/vtex-apps/store-graphql/pull/215
=> Add assembly options resolvers on OrderForm query

CHANGELOG.md, manifest.json, react/queries/product.gql
As the title said. 
This PR has an dependecy with the [GraphQl](https://github.com/vtex-apps/store-graphql/pull/225)
=> Add specificationGroups in product query

CHANGELOG.md, manifest.json, react/mutations/updateOrderFormShipping.gql, react/queries/orderForm.gql
=> fix shipping mutation response

CHANGELOG.md, manifest.json, react/mutations/addToCart.gql, react/mutations/updateItems.gql, react/queries/orderForm.gql
field is not used anymore and is causing bugs on link state, better to remove
depends on https://github.com/vtex-apps/minicart/pull/125
=> remove item metadata from order form queries/mutations

CHANGELOG.md, manifest.json, react/queries/product.gql, react/queries/search.gql
Depends on: https://github.com/vtex-apps/store-graphql/pull/257
=> Add discountHighlights field in search and product queries

CHANGELOG.md, manifest.json, react/mutations/addToCart.gql, react/mutations/updateItems.gql, react/mutations/updateOrderFormShipping.gql, react/queries/orderForm.gql
https://address--delivery.myvtex.com/
=> fetch checkin params from orderForm

CHANGELOG.md, manifest.json, react/mutations/addToCart.gql, react/mutations/updateItems.gql, react/queries/orderForm.gql
https://cartindex--storecomponents.myvtex.com/
related to
vtex-apps/product-summary#134
https://github.com/vtex-apps/minicart/pull/126
=> add cartIndex to orderForm queries

CHANGELOG.md, manifest.json, react/queries/productSearch.gql
Add separate param for the facets query and map.
Stable filters feature, see vtex-apps/search-result#150.
[Workspace](https://lucas--storecomponents.myvtex.com/clothing/shirts?map=c%2Cc).
=> Separate facets and products query and map

CHANGELOG.md, manifest.json, react/queries/product.gql, react/queries/productPreview.gql, react/queries/productSearch.gql, react/queries/productSearchV2.gql, react/queries/recommendationsAndBenefits.gql, react/queries/search.gql
Adds new fields for being consumed by breadcrumb for generating the links with translation support
=> Translation providers

CHANGELOG.md, manifest.json, react/queries/productSearchV2.gql
https://fidelis--invictastores.myvtex.com/
=> use hideUnavailableItems parameter on facets query

CHANGELOG.md, react/queries/productSearchV2.gql
The PowerReviews app relies on this field to query for reviews.
https://breno--storecomponents.myvtex.com/
=> Add field 'productReference' to 'productSearchV2' query

CHANGELOG.md, react/queries/product.gql, react/queries/productBenefits.gql, react/queries/recommendationsAndBenefits.gql
=> Adds `ProductUniqueIdentifier` parameter to product query

.prettierignore, CHANGELOG.md, react/Queries.js, react/queries/address.gql
=> add address query

CHANGELOG.md, react/queries/product.gql
Provide product videos to storefront. Related to https://github.com/vtex-apps/store-graphql/pull/385
This field is currently being ignored.
https://augusto--storecomponents.myvtex.com/work-shirt/p
=> Retrieve product videos from catalog

CHANGELOG.md, react/Queries.js, react/queries/UNSTABLE__productCategoryTree.gql, react/queries/product.gql
make us able to do category tree resolver on client side
https://bread--storecomponents.myvtex.com/classy--sunglasses/p
https://fidelis--exitocol.myvtex.com/celular-iphone-6s-64gb-rose-gold-100160624-mp/p
=> create category tree query

CHANGELOG.md, react/Queries.js, react/queries/searchMetadata.gql
https://fidteste--exitocol.myvtex.com/moda-y-accesorios/moda-nina/exterior-nina
view-source:https://fidteste--exitocol.myvtex.com/moda-y-accesorios/moda-nina/exterior-nina
see it returns with title as the name of the category from ssr
merge after graphql
=> add search metadata query

CHANGELOG.md, react/queries/product.gql
Depends on https://github.com/vtex-apps/search-graphql/pull/8
=> Add defaultValue to InputValue of the Product query

CHANGELOG.md, react/queries/productBenefits.gql, react/queries/productSearchV2.gql
https://badge--storecomponents.myvtex.com/
=> add product specification groups resolver to products queries

CHANGELOG.md, react/PWAContext.js, react/package.json, react/utils/webAppIndexedDB.js, react/yarn.lock
This reverts commit b6214c43b5ffe88f66f64f29e4908124adb4f7a3, reversing
changes made to 89a12f354de698f2f37bec357a7795e1854814cc.
Reverts https://github.com/vtex-apps/store-resources/pull/64
=> Revert "Merge pull request #64 from vtex-apps/feat/install-dismissed"

CHANGELOG.md, react/OrderFormContext.js, react/package.json
https://fidelis--storecomponents.myvtex.com/classic-shoes/p
Add item to cart, see it works
=> make orderFormConsumer use hook

manifest.json
Removes unnecessary runtime dependency
=> Removes runtime dependency #trivial

react/Queries.js, react/queries/facets.gql
Create facets query to be used in SearchQuery component
=> create facets query

CHANGELOG.md, react/queries/productSearch.gql, react/queries/productSearchV2.gql
=> Renames queries

CHANGELOG.md, manifest.json
=> Release v0.36.1

CHANGELOG.md, react/queries/productSearchV2.gql
https://fidelis--storecomponents.myvtex.com/classic?_q=classic&map=ft
=> add skusFilter var

CHANGELOG.md, react/queries/productSearchV2.gql
use priceRange resolver
https://pricerange--alssports.myvtex.com/clothing?map=c
=> use pricerange resolver

CHANGELOG.md, react/mutations/addToCart.gql
=> add utm and utmi params in addToCart query

CHANGELOG.md, react/queries/facets.gql
Add facetsBehavior on the `facets` parameters.
Works along with these:
https://github.com/vtex-apps/store/pull/398
https://github.com/vtex-apps/search-result/pull/290
https://github.com/vtex-apps/search-graphql/pull/39
[Workspace](https://iaronaraujo--storecomponents.myvtex.com/apparel---accessories/clothing/Black?map=c,c,specificationFilter_52)
=> Add ignoreSpecificationFilters

CHANGELOG.md, react/queries/productSearchV2.gql
https://skip--biscoind.myvtex.com/
=> add simulationBehavior to search query

CHANGELOG.md, react/mutations/addToCart.gql, react/mutations/updateItems.gql, react/queries/orderForm.gql
https://fidelis--worldwidegolf.myvtex.com/titleist-pro-v1x-custom-golf-balls-100007927/p?skuId=2090103
=> consume hasAttachment

CHANGELOG.md, react/queries/product.gql
=> fetch all SKUs images in product query

CHANGELOG.md, react/QueryProducts.js, react/queries/products.gql
https://fidelis--storecomponents.myvtex.com/
=> create products query

CHANGELOG.md, react/queries/products.gql
Make it available to control what price to show, if before or after interest
https://fidelis--storecomponents.myvtex.com/
=> add installment criteria param to products query

manifest.json
=> release v0.54.0

CHANGELOG.md, react/queries/product.gql
As the title says
Needs https://github.com/vtex-apps/search-graphql/pull/70
[Workspace](https://productprice--storecomponents.myvtex.com/fashion-eyeglasses/p)
=> Add spotPrice on product.gql

CHANGELOG.md, react/queries/product.gql
As the title says
Needs https://github.com/vtex-apps/search-graphql/pull/72
[Workspace](https://productprice--storecomponents.myvtex.com/fashion-eyeglasses/p)
=> Fixed problem caused by `0.56.0`

CHANGELOG.md, react/PWAContext.js
=> add workspace querystring in manifest href

CHANGELOG.md, react/queries/orderForm.gql
Adds productId for `orderForm` items
=> Adds productId

CHANGELOG.md, react/queries/productSearch.gql, react/queries/productSearchV2.gql, react/queries/productSearchV3.gql, react/queries/products.gql
Add `spotPrice` on the queries related to search.
[Workspace](https://iaronaraujo--storecomponents.myvtex.com/apparel---accessories/clothing/)
=> Add `spotPrice` on searches

CHANGELOG.md, react/queries/product.gql, react/queries/productBenefits.gql, react/queries/productSearchV2.gql, react/queries/productSearchV3.gql, react/queries/productSuggestions.gql, react/queries/products.gql
Add new fields to store-resources.
https://vtex.slack.com/archives/C9P4RMW6Q/p1594852833324400?thread_ts=1594852833.324300&cid=C9P4RMW6Q
https://breno--storecomponents.myvtex.com/shoes?_q=shoes&map=ft
=> Add originalName fields

CHANGELOG.md, react/queries/productSearchV3.gql
Add `correction` to the `productSearchV3` query.
[workspace](https://hiago--eriksbikeshop.myvtex.com/)
=> add correction

CHANGELOG.md, react/queries/productSuggestions.gql
Add the `productOriginVtex`to the `productSuggestions` query.
[Workspace](https://hiago--eriksbikeshop.myvtex.com/)
=> add productOriginVtex to the productSuggestions query

CHANGELOG.md, react/fragments/product.graphql
Provide field that is necessary do undeprecate the latest release of https://github.com/vtex-apps/product-specification-badges
https://brenovtex--cybelar.myvtex.com/guarda-roupa-imaginare-casal-em-mdp-6p-e-4g-santos-andira/p?__disableSSR=
=> Add originalName to Product's properties

CHANGELOG.md, manifest.json, react/QueryRecommendationShelf.js, react/queries/recommendationShelf.gql
Created to replace [the query on recommendation-shelf](https://github.com/vtex-apps/recommendation-shelf/blob/master/react/graphql/recommendation.gql)
[workspace](hiago--carrefourbrfood.myvtex.com)
=> add recommendation shelf query

CHANGELOG.md, react/queries/facetsV2.gql
Add initialAttributes to facets query
Depends on:
https://github.com/vtex-apps/search-resolver/pull/226
https://github.com/vtex-apps/search-graphql/pull/109
[Workspace](https://thalyta--carrefourbr.myvtex.com/admin/graphql-ide)
=> Add initialAttributes to FacetsV2

CHANGELOG.md, react/queries/productSearchV3.gql, react/queries/productSuggestions.gql, react/queries/products.gql
With the dynamic rules feature, the products will now have a new field called `rule`. This field will inform if a Merch rule was applied to the product
[workspace](https://hiago--storecomponents.myvtex.com/top/white?_q=asdfksjasq&fuzzy=0&initialMap=ft&initialQuery=asdfksjasq&map=ft,color&operator=and)
=> add rule to the productSearch and productSuggestions query

CHANGELOG.md, react/queries/sponsoredProducts.gql
Queries the field `advertisement` in `Product` on the `sponsoredProducts` query.
Gets more information about the ad that will be used by the Analytics script.
=> Feature: query advertisement field

CHANGELOG.md, react/fragments/product.graphql
Has Release Date of the products on productSummaryContext and productContext to have custom element like a labels of "NEW"
- https://releasedateinput--pcbox.myvtex.com/componentes-de-ordenador?__bindingAddress=www.pcbox.com/&order=OrderByReleaseDateDESC
```` typescript
const NewLabel:FC<{dayToShow : number}> = ({
dayToShow = 20
}) => {
const productContext:any = useProduct()
const isNew = React.useMemo(()=>{
if(!productContext.product?.releaseDate){
return false
}
const today = new Date();
const release = parseInt(productContext.product?.releaseDate);
const finalDay = new Date(new Date().setDate(today.getDate() -  dayToShow)).getTime()
const state = release > finalDay;
return state
},[productContext])
if(!isNew){
return null
}
return <label className={`dib fs-normal f7 bg-yellow white pa1 …
```
=> feat: releaseDate value added

CHANGELOG.md, react/QueryProductsTypes.tsx, react/fragments/ProductType.tsx, react/fragments/product.graphql, react/package.json, react/queries/productSearchV3.gql, react/queries/products.gql, react/yarn.lock
Adds advertisement options to `products` and `productSearch` queries.
They will be used to fetch sponsored products to shelves.
=> Feature: advertisement options

CHANGELOG.md, react/queries/facetsV2.gql
- ditto.
Depends on: https://github.com/vtex-apps/search-graphql/pull/143
- Allow A/B testing
[Workspace](https://felipe--biggy.myvtex.com/_v/private/vtex.search-graphql@0.64.0/graphiql/v1?query=query%20%7B%0A%20%20facets(variant%3A%22ds%22)%20%7B%0A%20%20%20%20priceRanges%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)
=> Added variant to facets query

CHANGELOG.md, manifest.json, react/QuerySponsoredBanners.js, react/queries/sponsoredBanners.gql
This PR creates and exports the sponsoredBanners query.
We need to create Sponsored Banners for our clients. To do this, it's necessary to request the banners data to Ad Server.
The store-resources create the query and exports it for Sponsored Banners component.
=> Feat: sponsored banners
