CHANGELOG.md
manifest.json
react/queries/search.gql

Add description into search field. This PR is related directly to this [one](https://github.com/vtex-apps/product-summary/pull/110).
The crash when the product summary is displaying a description of the product in the Search page.
[Workspace](https://productsummarydescription--storecomponents.myvtex.com/)

Add description into search field

---

CHANGELOG.md
manifest.json
react/Queries.js
react/queries/productSearchV2.gql

Add a new `productSearchV2` query, to use the `productSearch` of the store-grapqhl.
The information about the recordsFiltered was inside the `Facets` type, and it should be in the response of the products too.
The new file added is for backwards compatibility, so the version of the store and search-result using the `productSearch` don't break out of nowhere, because the expected types aren't paired up. The only difference between the V2 and the old one is the name of the query (`products` vs `productSearch`) and that the returned value has a `products` property with all properties of the other query, and a **new** `recordsFiltered` property.
[workspace](https://lucas--storecomponents.myvtex.com/shoes).

Add new product search v2 query

---

CHANGELOG.md
manifest.json
react/queries/productSearchV2.gql

https://app.clubhouse.io/vtex-dev/story/10619/add-prop-to-choose-not-to-show-unavailable-products-on-search-result
Before:
https://dev--invictastores.myvtex.com/impact-cases
After:
https://fidelis--invictastores.myvtex.com/impact-cases

use filterUnavailableBySegment on prod search v2

---

CHANGELOG.md
manifest.json
react/PWAContext.js

As the title says, a new context was created.
An elegant way of allowing apps to show the PWA installation prompt (without having to `window.postMessage`)
[Workspace](https://prompt--storecomponents.myvtex.com/admin/cms/storefront). Cancel the mini info-bar and click the buy button.

Add the usePWA hook (and the PWAContext)

---

react/queries/product.gql

Return productReference attribute in the query
Allow use productReference in default vtex query
We can add productReference to editor graphql IDE in product query
https://drive.google.com/file/d/1hOPGK1j6Lf2JCpSTgm_crJutyatJ3khQ/view?usp=sharing
* [ x ] New feature (a non-breaking change which adds functionality)

Add productReference to product.gql

---

CHANGELOG.md
react/queries/productSearchV2.gql

Return installments in search-result
Even when sending 'showInstallments' on product-summary, the installments don't appear.

Return installments on search

---

CHANGELOG.md
react/queries/productSearchV2.gql

Get the Product Properties in the SearchResult pages.
It should show the properties field in the Product.
[GraphiQL](https://vtexexito--prueba1.myvtex.com/_v/vtex.store-resources@0.15.1/graphiql/v1?operationName=search&variables=%7B%0A%20%20%22withFacets%22%3A%20true%2C%0A%20%20%22query%22%3A%20%22textil%22%2C%0A%20%20%22map%22%3A%20%22c%22%2C%0A%20%20%22orderBy%22%3A%20%22OrderByTopSaleDESC%22%2C%0A%20%20%22from%22%3A%200%2C%0A%20%20%22to%22%3A%209%2C%0A%20%20%22facetQuery%22%3A%20%22textil%22%2C%0A%20%20%22facetMap%22%3A%20%22c%22%0A%7D
)
[Query](https://paste.ofcode.org/yDRrD9VBgiLvQzk9vDp3iP) (Too long)

Add properties field in SearchProductsV2 query

---

CHANGELOG.md
react/OrderFormContext.js
react/queries/orderForm.gql

To avoid send multiple mutations setOrderFormCustomData, we update the query fields of orderForm and the PropTypes of OrderFormContext to support this functionality.
With the `customData` we can improve applications that use these queries.
1. Go to the page: https://orderform--tokstoklista.myvtex.com/casamento/guyas;
1. Open DevTools;
1. Open the Minicart file (./react/components/minicart/Minicart.js);
1. Add a breakpoint in line 122;
1. Scroll down the page and add a product to cart;
1. Debug.

Add customData in OrderFormContext

---

CHANGELOG.md
react/mutations/addToCart.gql
react/mutations/updateItems.gql
react/queries/orderForm.gql

Add fields `productRefId`, `additionalInfo`, `productCategoryIds`, `productCategories` to cart related queries: `orderForm`, `addToCart` and `updateItems`.
Make it possible to trigger addToCart and removeFromCart evens in Google Tag Manager.
https://breno--storecomponents.myvtex.com/
n/a

Add new fields to cart related queries

---

CHANGELOG.md
react/PWAContext.js
react/queries/pwaData.gql

As the title says.
Allow more options of events for the install prompt in PWA.
[Workspace](https://thay--storecomponents.myvtex.com)
This workspace is configured to prompt when an item is added to cart.
_Obs_: This prompt is showed only once, if you want to test more times, go to `chrome://flags/#enable-app-banners` and `chrome://flags/#bypass-app-banner-engagement-checks` in your chrome, and change these flags to **enabled**
Related: vtex-apps/store-components#570 , vtex-apps/admin-pages#261

Add promptOnCustomEvent in PWA Context

---

CHANGELOG.md
react/queries/product.gql
react/queries/productSearchV2.gql

Get condition and effects of Teasers on Product type.
[Workspace](https://vtexcamilo--exito.myvtex.com/_v/private/vtex.search-graphql@0.5.0/graphiql/v1?operationName=Product&variables=%7B%0A%20%20%22skipCategoryTree%22%3A%20true%2C%0A%20%20%22slug%22%3A%20%22nevera-himalaya-445-de-425-60-litros-haceb-no-frost-inox-951992%22%2C%0A%20%20%22identifier%22%3A%20%7B%0A%20%20%20%20%22field%22%3A%20%22id%22%2C%0A%20%20%20%20%22value%22%3A%20%22951992%22%0A%20%20%7D%0A%7D)
[Query](https://paste.ofcode.org/CstYmjm2MsP2knUdMFk6Bf)

Adding teaser details in Product and ProductSearchV2 queries

---

CHANGELOG.md
react/PWAContext.js
react/package.json
react/utils/webAppIndexedDB.js
react/yarn.lock

As the title says.
We are implementing components to promote installation of the web app and these components need to know when the app as already installed or installation was dismissed.
[Workspace](https://thay--storecomponents.myvtex.com/checkout/orderPlaced/?og=949500478939)

Block prompt when is already installed or user dismissed

---

CHANGELOG.md
react/queries/productSearchV2.gql

Add missing property of `items` in `products` from `productSearchV2`query.
This attribute is necessary in order to use `SKUSelector` inside of `ProductSummary`.
[workspace](https://skuinsummary--storecomponents.myvtex.com/classic?_q=classic&map=ft)

Add variations to product in query of productSearchV2

---

CHANGELOG.md
react/queries/productSearchV2.gql

Add more arguments to the `productSearchV2` query:
- `category`
- `collection`
- `specificationFilters`
Those arguments are useful for `ProductSummaryList`, which requires the same arguments that the `Shelf` component uses to perform its query for a product list.
https://victorhmp--storecomponents.myvtex.com/about-us

Add new filtering arguments to productSearchV2 query

---

CHANGELOG.md
react/queries/productSearchV2.gql

- titleTag and metaTagDescription are now fetched in their own query. They are unneeded. This is a minor performance boost.
https://title--exitocol.myvtex.com
title--samsungar.myvtex.com
https://title--boticario.myvtex.com/
https://title--tbb.myvtex.com/cabelos/tratamento
https://title--parquedpedro.myvtex.com/

remove title tag from productSearch query

---

CHANGELOG.md
react/PWAContext.js
react/package.json
react/utils/webAppIndexedDB.js
react/yarn.lock

This PR is the same as this [one](#64) which was [reverted](#65).
I added upgradeDB function on the `openDB` to be called when the database was never created before.
[workspace](https://thay--storecomponents.myvtex.com)

Block prompt when is already installed or user dismissed #64

---

CHANGELOG.md
react/queries/productSearchV2.gql

Make search query a bit more performant by default by only request SKUs available.
https://fidelis--tbb.myvtex.com/facial

make ALL_AVAILABLE default

---

CHANGELOG.md
manifest.json
react/PWAContext.js

Add installWebApp pixel event.
We need to measure and show how much PWA features contributed to the overall user experience on VTEX stores.
[Workspace](https://pwaevents2--storecomponents.myvtex.com/checkout/orderPlaced/?og=949500478939)
> This app is setup with the [PWA Google Tag manager App](https://github.com/vtex-apps/pwa-gtm-pixel/pull/1), so you can check using the gtm dataLayer.
1. Click 'install' on install banner at the bottom of the page
2. Choose the option you desire on the A2HS prompt
3. Open the console, type `dataLayer` and check if the event was added

add installWebApp pixel event

---

CHANGELOG.md
react/queries/orderForm.gql

Add `lastName` field to `clientProfileData` field and `userProfileId` field to `orderForm` query.
Those fields wore exposed by `store-graphql` and we were not fetching them, but now they are needed.
[Workspace](https://victorhmp--storecomponents.myvtex.com/_v/private/vtex.store-resources@0.40.0/graphiql/v1?operationName=orderForm)

Add new fields to orderForm query

---

CHANGELOG.md
react/queries/product.gql

Add new prop skuSpecifications on the Product query. Needs https://github.com/vtex-apps/search-graphql/pull/42
[Workspace](https://iaronaraujo--storecomponents.myvtex.com/classic-shoes/p)
Open the console and check that valuesFromContext -> product. skuSpecifications exists

Add `skuSpecifications` on `product`

---

CHANGELOG.md
manifest.json
react/queries/facets.gql

Add queryArgs to facets resolver
Added a field called queryArgs that has {query, map} values
We need a way to keep track of the old facets query and map values, since our new search URLs doesn't have the complete information anymore. This makes search-result understand both formats url formats the new one and de legacy ones.

Facets compatibility args for new search URL structures

---

CHANGELOG.md
react/queries/product.gql
react/queries/productSearchV2.gql

Add a new field `gifts` to the `productSearchV2` and `Product` queries.
This should enable us to develop a new app that needs that data, such as `vtex.product-gifts`.
This is an example implementation of `product-gifts`:
[Workspace](https://productgifts--storecomponents.myvtex.com/traveler-backpack/p)
Depends on:
- https://github.com/vtex-apps/search-graphql/pull/51

Query for a new `gifts` field added to `Offer` type from search-graphql

---

CHANGELOG.md
react/queries/product.gql

To add `estimatedDateArrival` to the result of the product query.
https://app.clubhouse.io/vtex/story/33405/add-estimateddatearrival-to-product-query
See slack thread: https://vtex.slack.com/archives/C9P4RMW6Q/p1583949574316900

Get product estimated arrival date in product query

---

react/PWAContext.js

Instead of doing the query and take processing time during the first page load, wait for the load event before firing the pwa query
https://fidelis--alssports.myvtex.com/

make pwa context use lazy query

---

CHANGELOG.md
react/queries/productSearchV2.gql

Make possible to alter the installments portion of the query behave differently if needed, without compromising existing functionalities
Installments with interest won't appear on search-result
https://everton--brasiltatica.myvtex.com/acessorios-para-armas/caixa-para-municao

Added InstallmentCriteria variable

---

CHANGELOG.md
react/queries/product.gql

Add `taxPercentage` on `product`
Needs:
https://github.com/vtex-apps/search-resolver/pull/15
https://github.com/vtex-apps/search-graphql/pull/80
[Workspace](https://productprice--storecomponents.myvtex.com/fashion-eyeglasses/p)

Add `taxPercentage` on `product`

---

CHANGELOG.md
react/mutations/addToCart.gql
react/mutations/updateItems.gql

Continuation of #109.
Add missing `productId`s in the mutation that return a orderform-like object .
1) goto https://kiwi--exitocol.myvtex.com/toner-para-muslos-verde-miniso-sport-100630688-mp/p
2) click in 'lo quiero''
3) Check if minicart renders the item quantity baloon
n/a

Add missing productId in updateItems and addItem

---

CHANGELOG.md
react/queries/productSearch.gql
react/queries/productSearchV2.gql
react/queries/productSearchV3.gql
react/queries/products.gql

Adds `taxPercentage` and `Tax` on `products`, `productSearch`, `productSearchV2` and `productSearchV3` queries.
https://github.com/vtex-apps/product-price/issues/27
[Workspace](https://productprice--storecomponents.myvtex.com/)
[exitocol](https://iaronaraujo--exitocol.myvtex.com/mercado/pollo-carne-y-pescado/pollo)
Check the shelf and search pages

Add tax attributes on search queries

---

CHANGELOG.md
react/queries/facetsV2.gql

There are some filters that should be hidden in UI. For example, the ones related to collections. This PR adds a `hidden` field to indicate which filter should be hidden.
⚠️ Please, do not merge it before:
- https://github.com/vtex-apps/search-resolver/pull/29
- https://github.com/vtex-apps/search-resolver/pull/28
- https://github.com/vtex-apps/search-graphql/pull/82
[Workspace](https://hiago--storecomponents.myvtex.com/apparel---accessories/clothing/)
✔️ | Type of Change
---|---
_ | Bug fix 
✔️ | New feature 
_ | Breaking change 
_ | Technical improvements

add hidden field

---

CHANGELOG.md
react/queries/productSearchV3.gql

Add the following snippet to the `productSearchV3` query, so that the SKU Selector component has access to this attribute when it's being used inside a `store.search` page.
```graphql
skuSpecifications {
field {
name
}
values {
name
}
}
```
The SKU Selector derives the available product variations from its nearest `ProductContext`. When its rendered inside of a `store.product` page, the SKU Selector has access to a `ProductContext` that was populated with the result of a `product` query, which includes this `skuSpecifications` field. It then uses the specifications received from the query to render itself. However, when the SKU Selector is rendered inside a `product-summary` (typically in the form of a `product-summary-sku-selector` block), for example in a `store.search` page, the …

Add 'skuSpecifications' field to 'productSearchV3' query

---

CHANGELOG.md
react/queries/productSearchV3.gql

- https://github.com/vtex-apps/search-graphql/pull/87
- https://github.com/vtex-apps/search-resolver/pull/57
- Update graphql version in `search-resolver@0.x`, 1.x and any other search-engine
The intelligent search has a feature called split. Basically, instead of showing one product with three possible colors, we show three products, each one with one color.
Before split:
After split:
This PR adds a new field called `selectedProperties`. This field has the properties that were selected after the split.
[Workspace](https://hiago--footnotes.myvtex.com/luna%20snake%20flat%20slingback?_q=Luna%20snake%20flat%20slingback&map=ft)
✔️ | Type of Change
---|---
_ | Bug fix 
✔️ | New feature 
_ | Breaking change 
_ | Technical improvements

add selectedProperties field to the product object

---

CHANGELOG.md
react/queries/product.gql
react/queries/productBenefits.gql
react/queries/productSearchV2.gql
react/queries/productSearchV3.gql
react/queries/productSuggestions.gql
react/queries/recommendationsAndBenefits.gql

Add `PaymentSystemName` to `Installments` in `Product` in order to use this value in the `vtex.product-price:product-installments` block
1. [workspace](https://installmentslist--storecomponents.myvtex.com/vintage-phone/p)
2. Open apollo devTools and check if the value is coming in the query

Fetch PaymentSystemName from Installments in Product query

---

CHANGELOG.md
react/queries/products.gql

Add new fields to the teasers from the `products` query. We are have this fields on the `productSearch` query, but they are missing on the `products` one.
https://hiago--realplaza.myvtex.com/miniso?map=ft

add teasers

---

CHANGELOG.md
react/queries/productSearchV3.gql

Add two new arguments to the `productSearchV3` query.
- `excludedPaymentMethods`
- `includedPaymentMethods`
These arguments were not being exposed to users, since our default queries did not include them. This should enable us to use these new arguments in `vtex.search-result`.
Go to this [workspace](https://victormiranda--storecomponents.myvtex.com/apparel---accessories/).

Add 'excludedPaymentMethods' and 'includedPaymentMethods' arguments to productSearchV3 query

---

CHANGELOG.md
react/QueryProductRecommendations.js
react/fragments/commertialOffer.graphql
react/fragments/installment.graphql
react/fragments/item.graphql
react/fragments/product.graphql
react/fragments/seller.graphql
react/queries/product.gql
react/queries/productRecommendations.gql
react/queries/productSearchV2.gql
react/queries/productSearchV3.gql
react/queries/productSuggestions.gql
react/queries/products.gql

Use fragments in Product fields, making it easier to add new fields across queries.
Sometimes we add a new field at one query and forget to update other queries that have a Product, this leads to some product-summary features not to work on some occasions due to a missing field.
Also, moved the [productRecommendations query of vtex.shelf](https://github.com/vtex-apps/shelf/blob/master/react/queries/productRecommendations.gql) to this repo.
Example of PRs that would be immediately solved:
- [Add `spotPrice` to `productRecommendations.gql` #235](https://github.com/vtex-apps/shelf/pull/235)
- [Cluster highlights #121](https://github.com/vtex-apps/store-resources/pull/121)
- [Add sellerName to products query #130](https://github.com/vtex-apps/store-resources/pull/130)
1. alssports which uses …

Use fragments

---

CHANGELOG.md
react/queries/facetsV2.gql

This PR adds some changes necessary to make the store setting enableFiltersFetchOptimization work. This setting is responsible for truncating facets after the 10th one and making it possible to fetch the rest with a refetch.
Making it possible to enable a setting to improve performance on the FilterNavigator
[Workspace](https://iaronaraujo--storecomponents.myvtex.com/apparel---accessories/clothing/)
Go to the workspace and then check on the graphql that in the FacetsV2 query the `from` value is 0 and `to` is 10 
Then, on the `Color` filter, click on `show 4 more` and notice that the query was re-fetched, updating the results with every facet available!
NEEDS
https://github.com/vtex-apps/search-graphql/pull/94
https://github.com/vtex-apps/search-resolver/pull/101

Add changes to make enableFiltersFetchOptimization

---

CHANGELOG.md
react/queries/productSuggestions.gql

`misspelled` and `operator` to the `productSuggestions` query.
[workspace](https://hiago--alssports.myvtex.com/)
By typing in the search-bar the query will be triggered

add misspelled and operator to the productSuggestions

---

CHANGELOG.md
react/fragments/product.graphql

Add `categoryId`  to `product` fragment. These weren't present in each product's context, preventing apps like `condition.layout` from working in the search product list.
https://kiwi--storecomponents.myvtex.com/apparel---accessories/
Open dev tools and looks for the `potato` log

Add `categoryId` to `product` fragment.

---

CHANGELOG.md
react/package.json
react/queries/productSuggestions.gql
react/yarn.lock

[Workspace](https://hideunavailable--checkoutio.myvtex.com/utmi?_q=utmi&map=ft)
- Type `utmi` in the autocomplete (which is an unavailable product)
- the product should not appear in the autocomplete suggestions
Depends on: 
https://github.com/vtex-apps/search-graphql/pull/101
https://github.com/vtex-apps/search-resolver/pull/153

Add hideUnavailableItems to productSuggestions

---

CHANGELOG.md
react/queries/productSuggestions.gql

The `productsuggestions` query was missing some product fields. I decided to use the fragments that we already have to solve this kind of problem once and for all.
[workspace](https://hiago--eriksbikeshop.myvtex.com/)

use fragments on productsuggestions query

---

CHANGELOG.md
react/queries/itemsWithSimulation.gql

Adds the `AvailableQuantity` to the `itemsWithSimulationQuery`.  This field is already available on https://github.com/vtex-apps/store-graphql/blob/d77ad82527b0c234a9fb45051b9452b315e38f43/graphql/types/Product.graphql#L175, we just need to add it to the query.
[Wroskpace](https://hiago--carrefourbrfood.myvtex.com/busca/leite)
1. Scroll the page until you are able to see a product price
2. Open the Apollo the dev tools and check the `itemsWithSimulation` query

add availablequantity to the itemswithsimulation

---

CHANGELOG.md
react/queries/facetsV2.gql

⚠️ Do not deploy this before bumping the [search-graphql version](https://github.com/vtex-apps/search-graphql/pull/106) in all resolvers.
Add the `categoryTreeBehavior` to the `facetsV2` query. We will use this field to determine if the back end should return the category tree
[workspace](https://categorytreebehavior--storecomponents.myvtex.com/apparel---accessories/)

add categorytreebehavior to the facets query

---

CHANGELOG.md
react/queries/facetsV2.gql

Depends on 
https://github.com/vtex-apps/search-resolver/pull/227
https://github.com/vtex-apps/search-graphql/pull/110
Now we have a feature to improve search performance that only takes a sampling of the results to get a faster facet query response. 
With this feature enabled for a store, if there is a query that has more results than the limit set by the store, we will only return a sample of that result. 
In these scenarios, it's possible that the amount of products for a facet is returned with a lower value than the actual amount of products for that facet. To avoid an inconsistency in what is displayed to the user, it's necessary for the component to know when only a sample of the data was taken and, in this case, we should not display the amount of products for the facet in the …

Add sampling to facetsv2

---

CHANGELOG.md
react/mutations/addToCart.gql
react/mutations/updateItems.gql
react/queries/orderForm.gql

Add checkout API priceDefinition structure in queries and mutations related to orderForm.
This PR should be merged only after this another one: https://github.com/vtex-apps/store-graphql/pull/557
Add these fields solve the presentation of item total when related to the rounding error problem
[Workspace](https://pricedefinition--vtexproject.myvtex.com/_v/private/vtex.store-resources@0.84.0/graphiql/v1?query=query%20%7B%0A%20%20searchOrderForm%20(%0A%20%20%20%20orderFormId%3A%2278f1aa981882432993c6877bbaa7fdd2%22%0A%20%20)%20%7B%0A%20%20%20%20items%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20sellingPrice%0A%20%20%20%20%20%20price%0A%20%20%20%20%20%20quantity%0A%20%20%20%20%20%20priceDefinition%20%7B%0A%20%20%20%20%20%20%20%20calculatedSellingPrice%0A%20%20%20%20%20%20%20%20sellingPric …

Add priceDefinition structure

---

CHANGELOG.md
react/queries/productSuggestions.gql

Add orderby to the productSuggestions query
https://vtex-dev.atlassian.net/browse/PER-2236
[Workspace](https://hiago--eriksbikeshop.myvtex.com/)
- https://github.com/vtex-apps/search-graphql/pull/115

add orderby to the productSuggestions query

---

CHANGELOG.md
react/queries/productSuggestions.gql

Add count to productSuggestions query, allowing the store to display more than 5 product suggestions.
Currently, this manipulation of how many products to display is done on the client. The query always returns 5 and if the maximum is less than 5, a slice is made. However, if the store wants to display more than 5 suggestions, this doesn't work.
- [Workspace](https://thalyta--ametllerorigen.myvtex.com/)
- Autocomplete should show 12 product suggestions

Add count to productSuggestions query

---

CHANGELOG.md
react/QueryProductsTypes.tsx
react/queries/products.gql

Add shippingOptions variable to `products` query
Depends on https://github.com/vtex-apps/search-graphql/pull/122
[Workspace](https://shippingoptions--biggy.myvtex.com/?__bindingAddress=biggy.myvtex.com/)

Add shippingOptions to products query

---

CHANGELOG.md
react/queries/sponsoredProducts.gql

Allow A/B testing via Osiris.
We need to include the argument `anonymousId` on `sponsoredProducts` query.
The following query including `anonymousId` should work:
```graphql
{
sponsoredProducts(fullText: "camisa", anonymousId:"a") {
brand
}
}
```
[Test it here](https://orem--biggy.myvtex.com/_v/private/vtex.store-resources@0.94.0/graphiql/v1?query=%7B%0A%20%20sponsoredProducts(fullText%3A%20%22camisa%22%2C%20anonymousId%3A%22a%22)%20%7B%0A%20%20%20%20brand%0A%20%20%7D%0A%7D).

Add `anonymousId` query argument for A/B testing

---

CHANGELOG.md
react/queries/autocompleteSearchSuggestions.gql
react/queries/productRecommendations.gql
react/queries/products.gql
react/queries/searchSuggestions.gql
react/queries/topSearches.gql

To be able to use the `searchState` param in more queries. This enables us to send user data into the search-resolver app easily from the front-end. Added to the following queries in this PR:
- `searchSuggestions`
- `products`
-  `productRecommendations`
- `topSearches`
- `autocompleteSearchSuggestions`
Currently, there is no way to get data from the front-end regarding the user's session into the search resolver directly through these queries. Having this feature to get data this way would help in analytics and to provide better and customized results to the user.
[Workspace](https://usercookie--worldwidegolf.myvtex.com/)

feat: add searchState param to more queries

---

CHANGELOG.md
react/queries/productSuggestions.gql

Passes advertisement options to product suggestions query so that we can add sponsored products in the autocomplete bar.
https://adsautocomplete--sjdigital.myvtex.com/

Feature: add advertisement options to product suggestions

---

react/queries/productSuggestions.gql

This pull request adds a small enhancement to the `query productSuggestions` GraphQL query. The change introduces the `searchId` field to the query response, allowing clients to access the unique identifier associated with a product search.

feat: add searchId to productSuggestions query response
